urls.py
from django.conf.urls import url, patterns, include
from django.contrib.auth.decorators import login_required
from incident import views

urlpatterns = patterns(
    "",
    url(
        regex=r"^create/$",
        view=login_required(views.IncidentCreateView.as_view()),
        name="incident_create",
    ),
    url(
        regex=r"^$",
        view=views.IncidentListView.as_view(),
        name='incident_list',
    ),
    url(
        regex=r"^(?P<pk>\d+)/$",
        view=views.IncidentDetailView.as_view(),
        name="incident_detail",
    ),
    url(
        regex=r"^update/(?P<pk>\d+)/$",
        view=login_required(views.IncidentUpdateView.as_view()),
        name="incident_update",
    ),
)

models.py
from django.db import models
from django.core.urlresolvers import reverse


class Incident(models.Model):
    CRITICAL = 0
    MAJOR = 1
    MINOR = 2
    ENQUIRY = 3

    SEVERITY_LEVEL = (
        (CRITICAL, 'Critical'),
        (MAJOR, 'Major'),
        (MINOR, 'Minor'),
        (ENQUIRY, 'Enquiry'),
    )
    date_time = models.DateTimeField(auto_now=True)
    is_resolved = models.BooleanField(default=False)
    title = models.CharField(max_length=255)
    text = models.TextField()
    severity_level = models.IntegerField(
        max_length=1,
        choices=SEVERITY_LEVEL,
        default=0)

    class Meta:
        app_label = 'incident'
        ordering = ['severity_level','date_time']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('incident:incident_detail', args=[self.id])

    def get_severity_level(self):
        return self.SEVERITY_LEVEL[self.severity_level][1]


class Update(models.Model):
    incident = models.ForeignKey('incident.Incident')
    date_time = models.DateTimeField(auto_now=True)
    text = models.TextField()

    class Meta:
        app_label = 'incident'
        ordering = ['incident', 'date_time']
    
    def __str__(self):
        return "%s-%s" % (self.incident, self.id)

forms.py
from django.forms import ModelForm
from django.forms.models import inlineformset_factory
from incident.models import Incident, Update


class IncidentUpdateForm(ModelForm):
    class Meta:
        model = Incident
        fields = ['is_resolved', ]

UpdateFormSet = inlineformset_factory(
    Incident,
    Update,
    extra=1, )

views.py
from django.http import HttpResponseRedirect
from django.views import generic
from incident.models import Incident
from incident.forms import UpdateFormSet, IncidentUpdateForm


class IncidentDetailView(generic.DetailView):
    model = Incident


class IncidentListView(generic.ListView):
    model = Incident
    paginate_by = 25


class IncidentCreateView(generic.CreateView):
    model = Incident


class IncidentUpdateView(generic.UpdateView):
    template_name = 'incident/incident_update.html'
    model = Incident
    form_class = IncidentUpdateForm

    def get(self, request, *args, **kwargs):
        """
        Handles GET requests and instantiates blank versions of the form
        and its inline formsets.
        """
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        update_form = UpdateFormSet()
        return self.render_to_response(
            self.get_context_data(form=form, update_form=update_form))

    def post(self, request, *args, **kwargs):
        """
        Handles POST requests, instantiating a form instance and its inline
        formsets with the passed POST variables and then checking them for
        validity.
        """
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        update_form = UpdateFormSet(self.request.POST)
        if (form.is_valid() and update_form.is_valid()):
            return self.form_valid(form, update_form)
        else:
            return self.form_invalid(form, update_form)

    def form_valid(self, form, update_form):
        self.object = form.save()
        update_form.instance = self.object
        update_form.save()
        return HttpResponseRedirect(self.object.get_absolute_url())

    def form_invalid(self, form, update_form):
        """
        Called if a form is invalid. Re-renders the context data with the
        data-filled forms and errors.
        """
        return self.render_to_response(
            self.get_context_data(form=form, update_form=update_form))

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>{% block page_title %}{% endblock %} | Open Source</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-dashboard.css' %}" rel="stylesheet">
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">A Project</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">List ... <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Stuff</a></li>
                <li><a href="#">Stuff</a></li>
                <li><a href="#">Stuff</a></li>
                <li><a href="#">Stuff</a></li>
                <li><a href="#">Stuff</a></li>
                <li><a href="{% url 'incident:incident_list' %}">incident</a></li>
                <li><a href="#">Stuff</a></li>
              </ul>
            </li>
            {% if user.is_authenticated %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Create ... <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Stuff</a></li>
                <li><a href="#">Stuff</a></li>
                <li><a href="#">Stuff</a></li>
                <li><a href="#">Stuff</a></li>
                <li><a href="#">Stuff</a></li>
                <li><a href="{% url 'incident:incident_create' %}">incident</a></li>
                <li><a href="#">Stuff</a></li>
              </ul>
            </li>
            {% endif %}
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </div>

    <div class="container-fluid">

        {% block content %}
        {% endblock %}

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-2.1.0.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block extra_js %}{% endblock extra_js %}
  </body>
</html>

templates/incident/incident_detail.html
{% extends 'base.html' %}

{% block page_title %}Incident: {{object}}{% endblock %}

{% block content %}
<div class="container">
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">
        <p><strong>Incident: {{object}}</strong></p>
      </div>
      <table class="table">
      <tr>
        <td><strong>Date and Time</strong></td>
        <td>{{ object.date_time }}</td>
      </tr>
      <tr>
        <td><strong>Severity</strong></td>
        <td>{{ object.get_severity_level }}</td>
      </tr>
      <tr>
        <td><strong>Resolved:</strong></td>
        <td>{{ object.is_resolved }}</td>
      </tr>
      <tr>
        <td><strong>Description</strong></td>
        <td>{{ object.text }}</td>
      </tr>
      </table>
    </div><!--./panel (Incident Details)-->

    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">
        <p><strong>Updates</strong></p>
      </div>
      <!-- Table -->
      <table class="table">
      <tr>
        <th>Date and Time</th>
        <th>Details</th>
      </tr>
      {% for update in object.update_set.all %}
      <tr>
        <td>{{ update.date_time }}</td>
        <td>{{ update.text }}</td>
      </tr>
      {% endfor %}
      </table>
      <hr />
      <a class="btn btn-danger hidden-print" href="{% url 'incident:incident_update' pk=object.id %}">Update Incident</a>
    </div><!--./panel (Updates)-->

    <div class="panel panel-default">
      <div class="panel-heading">
        <p><strong>Affected Items</strong></p>
      </div>
      <table class="table">
      <tr>
        <th>Object Type</th>
        <th>Object Details</th>
      </tr>

      {% for amodel in object.amodel_set.all %}
      <tr>
        <td>Object Type</td>
        <td><a class="btn btn-primary btn-block" href="{{ amodel.get_absolute_url }}">{{ amodel }}</a></td>
      </tr>
      {% endfor %}

      </table>
    </div><!--./panel (Affected Items)-->
  </div><!--./col-md-12-->

</div><!--./row-->
</div>

{% endblock content %}

templates/incident/incident_form.html
{% extends "base.html" %}

{% block page_title %}Create Incident{% endblock %}


{% block content %}
<h1>Incident Record</h1>
<form action="." method="POST">
   <table>{{ form }}{% csrf_token %}</table>
   <input type="submit" value="Go" />
</form>
{% endblock content %}

templates/incident/incident_list.html
{% extends "base.html" %}

{% block page_title %}Incident List{% endblock %}

{% block content %}
<table class="table">
  <tr>
    <th>Date Recorded</th>
    <th>Title</th>
    <th>Severity</th>
  </tr>
{% for incident in object_list %}
  <tr>
    <td>{{ incident.date_time }}</td>
    {% if incident.is_resolved %}
    <td><a class="btn btn-success btn-block" href={{ incident.get_absolute_url }}>{{ incident }}</td>
    {% else %}
    <td><a class="btn btn-warning btn-block" href={{ incident.get_absolute_url }}>{{ incident }}</td>
    {% endif %}
    <td>{{ incident.get_severity_level }}</td>
  </tr>
{% endfor %}
</table>
{% endblock %}

templates/incident/incident_update.html
{% extends 'base.html' %}

{% block page_title %}{{ object }}{% endblock %}

{% block content %}
        <h1>Incident: {{ object }}</h1>
        <form action="." method="post">{% csrf_token %}
            <div>
                {{ form }}
            </div>
            <fieldset>
                <legend>Update</legend>
                {{ update_form.management_form }}
                {{ update_form.non_form_errors }}
                {% for form in update_form %}
                    {{ form.id }}
                    {{ form }}
                {% endfor %}
            </fieldset>
            <hr />
            <input type="submit" value="Save" class="submit" />
        </form>
    </div>
{% endblock content %}